/* libplaylist.h generated by valac, the Vala compiler, do not modify */


#ifndef __LIBPLAYLIST_H__
#define __LIBPLAYLIST_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>

G_BEGIN_DECLS


#define PL_TYPE_LIST_TYPE (pl_list_type_get_type ())

#define PL_TYPE_RESULT (pl_result_get_type ())

#define PL_TYPE_DATA (pl_data_get_type ())
#define PL_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PL_TYPE_DATA, PlData))
#define PL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PL_TYPE_DATA, PlDataClass))
#define PL_IS_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PL_TYPE_DATA))
#define PL_IS_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PL_TYPE_DATA))
#define PL_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PL_TYPE_DATA, PlDataClass))

typedef struct _PlData PlData;
typedef struct _PlDataClass PlDataClass;
typedef struct _PlDataPrivate PlDataPrivate;

#define PL_TYPE_READER (pl_reader_get_type ())
#define PL_READER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PL_TYPE_READER, PlReader))
#define PL_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PL_TYPE_READER, PlReaderClass))
#define PL_IS_READER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PL_TYPE_READER))
#define PL_IS_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PL_TYPE_READER))
#define PL_READER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PL_TYPE_READER, PlReaderClass))

typedef struct _PlReader PlReader;
typedef struct _PlReaderClass PlReaderClass;
typedef struct _PlReaderPrivate PlReaderPrivate;

#define PL_TYPE_WRITER (pl_writer_get_type ())
#define PL_WRITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PL_TYPE_WRITER, PlWriter))
#define PL_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PL_TYPE_WRITER, PlWriterClass))
#define PL_IS_WRITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PL_TYPE_WRITER))
#define PL_IS_WRITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PL_TYPE_WRITER))
#define PL_WRITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PL_TYPE_WRITER, PlWriterClass))

typedef struct _PlWriter PlWriter;
typedef struct _PlWriterClass PlWriterClass;
typedef struct _PlWriterPrivate PlWriterPrivate;

typedef enum  {
	PL_READER_ERROR_UNKNOWN_TYPE,
	PL_READER_ERROR_SOMETHING_ELSE
} PlReaderError;
#define PL_READER_ERROR pl_reader_error_quark ()
typedef enum  {
	PL_WRITER_ERROR_UNKNOWN_TYPE,
	PL_WRITER_ERROR_SOMETHING_ELSE
} PlWriterError;
#define PL_WRITER_ERROR pl_writer_error_quark ()
typedef enum  {
	PL_LIST_TYPE_UNKNOWN = 0,
	PL_LIST_TYPE_IGNORED,
	PL_LIST_TYPE_M3U,
	PL_LIST_TYPE_PLS,
	PL_LIST_TYPE_ASX,
	PL_LIST_TYPE_XSPF
} PlListType;

typedef enum  {
	PL_RESULT_UNHANDLED = 0,
	PL_RESULT_ERROR,
	PL_RESULT_IGNORED,
	PL_RESULT_SUCCESS
} PlResult;

struct _PlData {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PlDataPrivate * priv;
	char** urls;
	gint urls_length1;
	char* title;
	char* author;
	char* genre;
	char* album;
	char* volume;
	char* duration;
	char* starttime;
	char* copyright;
	PlListType playlist_type;
};

struct _PlDataClass {
	GTypeClass parent_class;
	void (*finalize) (PlData *self);
};

struct _PlReader {
	GObject parent_instance;
	PlReaderPrivate * priv;
};

struct _PlReaderClass {
	GObjectClass parent_class;
};

struct _PlWriter {
	GObject parent_instance;
	PlWriterPrivate * priv;
};

struct _PlWriterClass {
	GObjectClass parent_class;
};


GQuark pl_reader_error_quark (void);
GQuark pl_writer_error_quark (void);
GType pl_list_type_get_type (void);
GType pl_result_get_type (void);
extern gboolean pl_debug;
gpointer pl_data_ref (gpointer instance);
void pl_data_unref (gpointer instance);
GParamSpec* pl_param_spec_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void pl_value_set_data (GValue* value, gpointer v_object);
void pl_value_take_data (GValue* value, gpointer v_object);
gpointer pl_value_get_data (const GValue* value);
GType pl_data_get_type (void);
PlData* pl_data_new (void);
PlData* pl_data_construct (GType object_type);
char* pl_data_get_next_url (PlData* self);
GType pl_reader_get_type (void);
PlReader* pl_reader_new (const char* playlist_uri);
PlReader* pl_reader_construct (GType object_type, const char* playlist_uri);
void pl_reader_read (PlReader* self, GError** error);
void pl_reader_read_async (PlReader* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void pl_reader_read_finish (PlReader* self, GAsyncResult* _res_, GError** error);
char** pl_reader_get_uris (PlReader* self, int* result_length1);
char* pl_reader_get_title (PlReader* self);
char* pl_reader_get_author (PlReader* self);
char* pl_reader_get_genre (PlReader* self);
char* pl_reader_get_album (PlReader* self);
char* pl_reader_get_volume (PlReader* self);
char* pl_reader_get_duration (PlReader* self);
char* pl_reader_get_starttime (PlReader* self);
char* pl_reader_get_copyright (PlReader* self);
PlListType pl_reader_get_ptype (PlReader* self);
const char* pl_reader_get_uri (PlReader* self);
GType pl_writer_get_type (void);
PlWriter* pl_writer_new (PlListType ptype);
PlWriter* pl_writer_construct (GType object_type, PlListType ptype);
PlResult pl_writer_write_to_file (PlWriter* self);
void pl_writer_write_asyn (PlWriter* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
PlResult pl_writer_write_asyn_finish (PlWriter* self, GAsyncResult* _res_);
const char* pl_writer_get_uri (PlWriter* self);


G_END_DECLS

#endif
