.TH "xnoise" 1
.SH NAME
xnoise \- Media player for Gtk+
.SH SYNOPSIS
.B xnoise
[OPTIONS]
[FILES]

.SH DESCRIPTION
Xnoise is a media player for Gtk+. It uses the gstreamer framework and stores
media files in a database. It is used to quickly manage large collections.


.SH OPTIONS
.TP
\fB\-V\fR, \fB\-\-version\fR
Show the application's version.
.TP
\fB\-h\fR, \fB\-\-hidden\-window\fR
Start the application with hidden window.
.TP
\fB\-p\fR, \fB\-\-plugin\-info\fR
Show loaded and activated plugins on app start.
.TP
\fB\-N\fR, \fB\-\-no\-plugins\fR
Start without loading any plugins.
.TP
\fB\-D\fR, \fB\-\-no\-dbus\fR
Start without using the onboard dbus interface.
.TP
\fB\-R\fR, \fB\-\-reset\fR
Reset all settings.
.TP
\fB\-t\fR, \fB\-\-play\-pause\fR
Toggle Playback.
.TP
\fB\-s\fR, \fB\-\-stop\fR
Stop playback.
.TP
\fB\-n\fR, \fB\-\-next\fR
Goto next track.
.TP
\fB\-e\fR, \fB\-\-previous\fR
Goto previous track.
.TP
\fB\-q\fR, \fB\-\-quit\fR
Quit a running instance of xnoise.
.TP
\fB\-?\fR, \fB\-\-help\fR
Show help options

.SH AUTHORS
Jörn Magens <shuerhaaken@googlemail.com>

Man page written to conform with Debian by Jörn Magens.
