.TH "xnoise" 1
.SH NAME
xnoise \- Media player for Gtk+
.SH SYNOPSIS
.B xnoise
[OPTIONS]
[FILES]

.SH DESCRIPTION
Xnoise is a media player for Gtk+. It uses the gstreamer framework and stores
media files in a database.


.SH OPTIONS
.IP -V
Show version info.
.IP -p
Show loaded and activated plugins on app start.
.IP -N
Start without loding any plugins.
.IP -R
Reset all settings.

.SH AUTHORS
Jörn Magens <shuerhaaken@googlemail.com>

Man page written to conform with Debian by Jörn Magens.
